name: PHP Project CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict || true

    - name: Lint PHP
      run: |
        find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l

    - name: Build Docker image
      run: |
        docker build -t my-php-project:${{ github.sha }} .
        
    - name: Test Docker image
      run: |
        docker run --rm my-php-project:${{ github.sha }} php -v

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: my-php-project:latest
        
    - name: Deploy info
      run: |
        echo "In a real-world scenario, this step would deploy the application to a server"
        echo "Options include:"
        echo "- Deploying to a cloud hosting provider (AWS, Azure, GCP)"
        echo "- Using SSH to deploy to a dedicated server"
        echo "- Using a service like Heroku or DigitalOcean App Platform"